name: Build

on:
  push:
    branches: 
      - master
    paths:
      - FastMM4.pas
      - FastMM4Messages.pas
      - FastMM4Options.inc

  workflow_dispatch:

jobs:
  build_linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update apt sources
        run: sudo apt-get update

      - name: Install Free Pascal
        run: sudo apt-get install -y fpc

      - name: Compile a simple demo in ObjFPC mode
        run: cd $GITHUB_WORKSPACE/Tests/Simple && fpc -B -MObjFPC -Tlinux -Px86_64 -O4 SimpleTest.dpr

      - name: Compile a simple demo in Delphi mode
        run: cd $GITHUB_WORKSPACE/Tests/Simple && fpc -B -Mdelphi -Tlinux -Px86_64 -O4 SimpleTest.dpr

      - name: Compile with various defined options
        run: |
          cd $GITHUB_WORKSPACE/Tests/Simple
          fpc -B -Mdelphi -Tlinux -Px86_64 -dDEBUG -g -O- SimpleTest.dpr

      - name: Compile with -dDEBUG -g -dFullDebugMode
        run: |
          cd $GITHUB_WORKSPACE/Tests/Simple
          fpc -B -Mdelphi -Tlinux -Px86_64 -dDEBUG -g -dFullDebugMode -O- SimpleTest.dpr

      - name: Compile with -dFullDebugMode
        run: |
          cd $GITHUB_WORKSPACE/Tests/Simple
          fpc -B -Mdelphi -Tlinux -Px86_64 -dFullDebugMode -O4 SimpleTest.dpr

      - name: Compile with -dAlign16Bytes
        run: |
          cd $GITHUB_WORKSPACE/Tests/Simple
          fpc -B -Mdelphi -Tlinux -Px86_64 -dAlign16Bytes -O4 SimpleTest.dpr

      - name: Compile with -dAlign32Bytes
        run: |
          cd $GITHUB_WORKSPACE/Tests/Simple
          fpc -B -Mdelphi -Tlinux -Px86_64 -dAlign32Bytes -O4 SimpleTest.dpr

      - name: Compile with -dDontUseCustomFixedSizeMoveRoutines
        run: |
          cd $GITHUB_WORKSPACE/Tests/Simple
          fpc -B -Mdelphi -Tlinux -Px86_64 -dDontUseCustomFixedSizeMoveRoutines -O4 SimpleTest.dpr

      - name: Compile with -dDontUseCustomVariableSizeMoveRoutines
        run: |
          cd $GITHUB_WORKSPACE/Tests/Simple
          fpc -B -Mdelphi -Tlinux -Px86_64 -dDontUseCustomVariableSizeMoveRoutines -O4 SimpleTest.dpr

      - name: Compile with -dForceSingleThreaded
        run: |
          cd $GITHUB_WORKSPACE/Tests/Simple
          fpc -B -Mdelphi -Tlinux -Px86_64 -dForceSingleThreaded -O4 SimpleTest.dpr

      - name: Compile with -dDisablePauseAndSwitchToThread
        run: |
          cd $GITHUB_WORKSPACE/Tests/Simple
          fpc -B -Mdelphi -Tlinux -Px86_64 -dDisablePauseAndSwitchToThread -O4 SimpleTest.dpr

      - name: Compile with -dDontUseSmallBlocksLockedCriticalSection
        run: |
          cd $GITHUB_WORKSPACE/Tests/Simple
          fpc -B -Mdelphi -Tlinux -Px86_64 -dDontUseSmallBlocksLockedCriticalSection -O4 SimpleTest.dpr

      - name: Compile with -dDontUseMediumBlocksLockedCriticalSection
        run: |
          cd $GITHUB_WORKSPACE/Tests/Simple
          fpc -B -Mdelphi -Tlinux -Px86_64 -dDontUseMediumBlocksLockedCriticalSection -O4 SimpleTest.dpr

      - name: Compile with -dDontUseLargeBlocksLockedCriticalSection
        run: |
          cd $GITHUB_WORKSPACE/Tests/Simple
          fpc -B -Mdelphi -Tlinux -Px86_64 -dDontUseLargeBlocksLockedCriticalSection -O4 SimpleTest.dpr

      - name: Compile with -dDontUseASMVersion
        run: |
          cd $GITHUB_WORKSPACE/Tests/Simple
          fpc -B -Mdelphi -Tlinux -Px86_64 -dDontUseASMVersion -O4 SimpleTest.dpr

      - name: Compile with -dDontUseASMVersion
        run: |
          cd $GITHUB_WORKSPACE/Tests/Simple
          fpc -B -Mdelphi -Tlinux -Px86_64 -dDontUseASMVersion -O4 SimpleTest.dpr

      - name: Compile with -dDisableMemoryLeakReporting
        run: |
          cd $GITHUB_WORKSPACE/Tests/Simple
          fpc -B -Mdelphi -Tlinux -Px86_64 -dDisableMemoryLeakReporting -O4 SimpleTest.dpr

      - name: Compile with -dRequireIDEPresenceForLeakReporting
        run: |
          cd $GITHUB_WORKSPACE/Tests/Simple
          fpc -B -Mdelphi -Tlinux -Px86_64 -dRequireIDEPresenceForLeakReporting -O4 SimpleTest.dpr


  build_windows:
    runs-on: windows-latest
    env:
      fpc: C:\FPC\3.2.2\bin\i386-win32\fpc.exe

    steps:
      - uses: actions/checkout@v4

      - name: Download FreePascal installer
        run: |
            & 'curl.exe' @('-L', '-o', 'fpc_installer.exe', 'https://sourceforge.net/projects/freepascal/files/Win32/3.2.2/fpc-3.2.2.win32.and.win64.exe/download')

      - name: Install FreePascal silently
        run: |
          & '.\fpc_installer.exe' @('/VERYSILENT', '/SUPPRESSMSGBOXES', '/NORESTART', '/SP-')

      - name: Compile by FreePascal 32-bit with -dDisableAsmCodeAlign
        run: |
          cd $Env:GITHUB_WORKSPACE/Tests/Simple
          & '${{ env.fpc }}' @('-B', '-Mdelphi', '-Twin32', '-Pi386', '-dDisableAsmCodeAlign', 'SimpleTest.dpr')

      - name: Compile by FreePascal 32-bit with -dDEBUG 
        run: |
          cd $Env:GITHUB_WORKSPACE/Tests/Simple
          & '${{ env.fpc }}' @('-B', '-Mdelphi', '-Twin32', '-Pi386', '-dDEBUG', '-g', '-O-', 'SimpleTest.dpr')

      - name: Compile by FreePascal 32-bit with -dDEBUG -dFullDebugMode
        run: |
          cd $Env:GITHUB_WORKSPACE/Tests/Simple
          & '${{ env.fpc }}' @('-B', '-Mdelphi', '-Twin32', '-Pi386', '-dDEBUG', '-g', '-dFullDebugMode', '-O-', 'SimpleTest.dpr')

      - name: Compile by FreePascal 32-bit with -dFullDebugMode but not DEBUG
        run: |
          cd $Env:GITHUB_WORKSPACE/Tests/Simple
          & '${{ env.fpc }}' @('-B', '-Mdelphi', '-Twin32', '-Pi386', '-dFullDebugMode', '-O4', 'SimpleTest.dpr')

      - name: Compile by FreePascal 32-bit with -dAlign16Bytes
        run: |
          cd $Env:GITHUB_WORKSPACE/Tests/Simple
          & '${{ env.fpc }}' @('-B', '-Mdelphi', '-Twin32', '-Pi386', '-dAlign16Bytes', '-O4', 'SimpleTest.dpr')

      - name: Compile by FreePascal 32-bit with -dAlign32Bytes 
        run: |
          cd $Env:GITHUB_WORKSPACE/Tests/Simple
          & '${{ env.fpc }}' @('-B', '-Mdelphi', '-Twin32', '-Pi386', '-dAlign32Bytes', '-O4', 'SimpleTest.dpr')

      - name: Compile by FreePascal 32-bit with -dDontUseCustomFixedSizeMoveRoutines
        run: |
          cd $Env:GITHUB_WORKSPACE/Tests/Simple
          & '${{ env.fpc }}' @('-B', '-Mdelphi', '-Twin32', '-Pi386', '-dDontUseCustomFixedSizeMoveRoutines', '-O4', 'SimpleTest.dpr')

      - name: Compile by FreePascal 32-bit with -dDontUseCustomVariableSizeMoveRoutines
        run: |
          cd $Env:GITHUB_WORKSPACE/Tests/Simple
          & '${{ env.fpc }}' @('-B', '-Mdelphi', '-Twin32', '-Pi386', '-dDontUseCustomVariableSizeMoveRoutines', '-O4', 'SimpleTest.dpr')

      - name: Compile by FreePascal 32-bit with -dForceSingleThreaded
        run: |
          cd $Env:GITHUB_WORKSPACE/Tests/Simple
          & '${{ env.fpc }}' @('-B', '-Mdelphi', '-Twin32', '-Pi386', '-dForceSingleThreaded', '-O4', 'SimpleTest.dpr')

      - name: Compile by FreePascal 32-bit with -dDisablePauseAndSwitchToThread 
        run: |
          cd $Env:GITHUB_WORKSPACE/Tests/Simple 
          & '${{ env.fpc }}' @('-B', '-Mdelphi', '-Twin32', '-Pi386', '-dDisablePauseAndSwitchToThread', '-O4', 'SimpleTest.dpr')

      - name: Compile by FreePascal 32-bit with -dDontUseSmallBlocksLockedCriticalSection
        run: |
          cd $Env:GITHUB_WORKSPACE/Tests/Simple
          & '${{ env.fpc }}' @('-B', '-Mdelphi', '-Twin32', '-Pi386', '-dDontUseSmallBlocksLockedCriticalSection', '-O4', 'SimpleTest.dpr')

      - name: Compile by FreePascal 32-bit with -dDontUseMediumBlocksLockedCriticalSection 
        run: |
          cd $Env:GITHUB_WORKSPACE/Tests/Simple
          & '${{ env.fpc }}' @('-B', '-Mdelphi', '-Twin32', '-Pi386', '-dDontUseMediumBlocksLockedCriticalSection', '-O4', 'SimpleTest.dpr')

      - name: Compile by FreePascal 32-bit with -dDontUseLargeBlocksLockedCriticalSection
        run: |
          cd $Env:GITHUB_WORKSPACE/Tests/Simple
          & '${{ env.fpc }}' @('-B', '-Mdelphi', '-Twin32', '-Pi386', '-dDontUseLargeBlocksLockedCriticalSection', '-O4', 'SimpleTest.dpr')

      - name: Compile by FreePascal 32-bit with -dDontUseASMVersion
        run: |
          cd $Env:GITHUB_WORKSPACE/Tests/Simple
          & '${{ env.fpc }}' @('-B', '-Mdelphi', '-Twin32', '-Pi386', '-dDontUseASMVersion', '-O4', 'SimpleTest.dpr')

      - name: Compile by FreePascal 32-bit with -dDisableMemoryLeakReporting
        run: |
          cd $Env:GITHUB_WORKSPACE/Tests/Simple
          & '${{ env.fpc }}' @('-B', '-Mdelphi', '-Twin32', '-Pi386', '-dDisableMemoryLeakReporting', '-O4', 'SimpleTest.dpr')

      - name: Compile by FreePascal 32-bit with -dRequireIDEPresenceForLeakReporting
        run: |
          cd $Env:GITHUB_WORKSPACE/Tests/Simple
          & '${{ env.fpc }}' @('-B', '-Mdelphi', '-Twin32', '-Pi386', '-dRequireIDEPresenceForLeakReporting', '-O4', 'SimpleTest.dpr')

      - name: Compile AVX-512 Assembly
        run: |
          cd $Env:GITHUB_WORKSPACE
          & 'nasm.exe' @('-Ox', '-Ov', '-f', 'win64', 'FastMM4_AVX512.asm')

      - name: Compile by FreePascal 64-bit with DisableAVX512 to test .noframe
        run: |
          cd $Env:GITHUB_WORKSPACE/Tests/Simple
          & '${{ env.fpc }}' @('-B', '-Mdelphi', '-Twin64', '-Px86_64', '-dDisableAVX512', '-O4', 'SimpleTest.dpr')

      - name: Compile by FreePascal 64-bit with -dDisableAsmCodeAlign
        run: |
          cd $Env:GITHUB_WORKSPACE/Tests/Simple
          & '${{ env.fpc }}' @('-B', '-Mdelphi', '-Twin64', '-Px86_64', '-dDisableAsmCodeAlign', '-O4', 'SimpleTest.dpr')

      - name: Compile by FreePascal 64-bit with -dDEBUG 
        run: |
          cd $Env:GITHUB_WORKSPACE/Tests/Simple
          & '${{ env.fpc }}' @('-B', '-Mdelphi', '-Twin64', '-Px86_64', '-dDEBUG', '-g', '-O-', 'SimpleTest.dpr')

      - name: Compile by FreePascal 64-bit with -dDEBUG -dFullDebugMode
        run: |
          cd $Env:GITHUB_WORKSPACE/Tests/Simple
          & '${{ env.fpc }}' @('-B', '-Mdelphi', '-Twin64', '-Px86_64', '-dDEBUG', '-g', '-dFullDebugMode', '-O-', 'SimpleTest.dpr')

      - name: Compile by FreePascal 64-bit with -dFullDebugMode but not DEBUG
        run: |
          cd $Env:GITHUB_WORKSPACE/Tests/Simple
          & '${{ env.fpc }}' @('-B', '-Mdelphi', '-Twin64', '-Px86_64', '-dFullDebugMode', '-O4', 'SimpleTest.dpr')

      - name: Compile by FreePascal 64-bit with -dAlign16Bytes
        run: |
          cd $Env:GITHUB_WORKSPACE/Tests/Simple
          & '${{ env.fpc }}' @('-B', '-Mdelphi', '-Twin64', '-Px86_64', '-dAlign16Bytes', '-O4', 'SimpleTest.dpr')

      - name: Compile by FreePascal 64-bit with -dAlign32Bytes 
        run: |
          cd $Env:GITHUB_WORKSPACE/Tests/Simple
          & '${{ env.fpc }}' @('-B', '-Mdelphi', '-Twin64', '-Px86_64', '-dAlign32Bytes', '-O4', 'SimpleTest.dpr')

      - name: Compile by FreePascal 64-bit with -dDontUseCustomFixedSizeMoveRoutines
        run: |
          cd $Env:GITHUB_WORKSPACE/Tests/Simple
          & '${{ env.fpc }}' @('-B', '-Mdelphi', '-Twin64', '-Px86_64', '-dDontUseCustomFixedSizeMoveRoutines', '-O4', 'SimpleTest.dpr')

      - name: Compile by FreePascal 64-bit with -dDontUseCustomVariableSizeMoveRoutines
        run: |
          cd $Env:GITHUB_WORKSPACE/Tests/Simple
          & '${{ env.fpc }}' @('-B', '-Mdelphi', '-Twin64', '-Px86_64', '-dDontUseCustomVariableSizeMoveRoutines', '-O4', 'SimpleTest.dpr')

      - name: Compile by FreePascal 64-bit with -dForceSingleThreaded
        run: |
          cd $Env:GITHUB_WORKSPACE/Tests/Simple
          & '${{ env.fpc }}' @('-B', '-Mdelphi', '-Twin64', '-Px86_64', '-dForceSingleThreaded', '-O4', 'SimpleTest.dpr')

      - name: Compile by FreePascal 64-bit with -dDisablePauseAndSwitchToThread 
        run: |
          cd $Env:GITHUB_WORKSPACE/Tests/Simple 
          & '${{ env.fpc }}' @('-B', '-Mdelphi', '-Twin64', '-Px86_64', '-dDisablePauseAndSwitchToThread', '-O4', 'SimpleTest.dpr')

      - name: Compile by FreePascal 64-bit with -dDontUseSmallBlocksLockedCriticalSection
        run: |
          cd $Env:GITHUB_WORKSPACE/Tests/Simple
          & '${{ env.fpc }}' @('-B', '-Mdelphi', '-Twin64', '-Px86_64', '-dDontUseSmallBlocksLockedCriticalSection', '-O4', 'SimpleTest.dpr')

      - name: Compile by FreePascal 64-bit with -dDontUseMediumBlocksLockedCriticalSection 
        run: |
          cd $Env:GITHUB_WORKSPACE/Tests/Simple
          & '${{ env.fpc }}' @('-B', '-Mdelphi', '-Twin64', '-Px86_64', '-dDontUseMediumBlocksLockedCriticalSection', '-O4','SimpleTest.dpr')

      - name: Compile by FreePascal 64-bit with -dDontUseLargeBlocksLockedCriticalSection
        run: |
          cd $Env:GITHUB_WORKSPACE/Tests/Simple
          & '${{ env.fpc }}' @('-B', '-Mdelphi', '-Twin64', '-Px86_64', '-dDontUseLargeBlocksLockedCriticalSection', '-O4','SimpleTest.dpr')

      - name: Compile by FreePascal 64-bit with -dDontUseASMVersion
        run: |
          cd $Env:GITHUB_WORKSPACE/Tests/Simple
          & '${{ env.fpc }}' @('-B', '-Mdelphi', '-Twin64', '-Px86_64', '-dDontUseASMVersion', '-O4', 'SimpleTest.dpr')

      - name: Compile by FreePascal 64-bit with -dDisableMemoryLeakReporting
        run: |
          cd $Env:GITHUB_WORKSPACE/Tests/Simple
          & '${{ env.fpc }}' @('-B', '-Mdelphi', '-Twin64', '-Px86_64', '-dDisableMemoryLeakReporting', '-O4', 'SimpleTest.dpr')

      - name: Compile by FreePascal 64-bit with -dRequireIDEPresenceForLeakReporting
        run: |
          cd $Env:GITHUB_WORKSPACE/Tests/Simple
          & '${{ env.fpc }}' @('-B', '-Mdelphi', '-Twin64', '-Px86_64', '-dRequireIDEPresenceForLeakReporting', '-O4', 'SimpleTest.dpr')
